/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/moneyBag.glb --transform 
Files: ./public/moneyBag.glb [11.67MB] > C:\Users\arpit\OneDrive\Desktop\NiveshSahayak\moneyBag-transformed.glb [395.69KB] (97%)
Author: aniljaco (https://sketchfab.com/aniljaco)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/money-bag-anil-f742275b6b1842b0af59c3950d422081
Title: Money bag -  Anil
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({anim}) {
  const { nodes, materials } = useGLTF('/moneyBag-transformed.glb')
  return (
    <group dispose={null} position={[anim.mx,-2.5,0.3]} scale={0.01} rotation={[0,Math.PI/1.5,0]}>
      <mesh geometry={nodes.Cube_Bag_0.geometry} material={materials.material} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.BezierCurve001_Rope_0.geometry} material={materials.Rope} position={[-7.606, 133.504, 3.237]} rotation={[-Math.PI / 2, 0, 0]} scale={20.063} />
      <mesh geometry={nodes.Text_Dol_0.geometry} material={materials.material_2} position={[-4.026, 53.933, -62.593]} rotation={[3.107, 0.155, -Math.PI]} scale={100} />
    </group>
  )
}

useGLTF.preload('/moneyBag-transformed.glb')
